### ISSUE TITLE
Unable to download subtitle for "live_chat" and UnicodeDecodeError

### ISSUE THREAD

**Issue by believableapparent** [pukkandan/yt-dlp#44] opened 2021-02-01 17:54 UTC
## Checklist

- [x] I've verified that I'm running yt-dlp version **2021.01.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dlc -o "%(autonumber)s %(upload_date)s %(title)s/%(id)s" --write-description --write-info-json --write-all-thumbnails --format "bestvideo+(bestaudio[asr=48000]/bestaudio)/bestaudio[ext=opus]/best" --sleep-interval 5 --max-sleep-interval 30 --ignore-errors --no-continue --no-overwrites --all-subs --merge-output-format "mkv" -v KKushcL0LEM 
[debug] Command-line config: [u'-o', u'%(autonumber)s %(upload_date)s %(title)s/%(id)s', u'--write-description', u'--write-info-json', u'--write-all-thumbnails', u'--format', u'bestvideo+(bestaudio[asr=48000]/bestaudio)/bestaudio[ext=opus]/best', u'--sleep-interval', u'5', u'--max-sleep-interval', u'30', u'--ignore-errors', u'--no-continue', u'--no-overwrites', u'--all-subs', u'--merge-output-format', u'mkv', u'-v', u'KKushcL0LEM']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.01.29
[debug] Git HEAD: 6cfff5e
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube] KKushcL0LEM: Downloading webpage
[debug] Sort order given by user: 
[debug] Formats sorted by: lang, quality, hasvid, ie_pref, res, fps, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 303+251
[info] Writing video description to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.description
[info] Writing video subtitles to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.live_chat.json
[debug] Invoking downloader on None
[youtube_live_chat_replay] Downloading live chat
[youtube_live_chat_replay] Total fragments: unknown (live)
[download] Destination: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.live_chat.json
[download] 683.57KiB at 219.21KiB/s (00:05)WARNING: Unable to download subtitle for "live_chat": HTTP Error 404: Not Found
[info] Writing video metadata as JSON to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.info.json
[youtube] KKushcL0LEM: Downloading thumbnail 0 ...
[youtube] KKushcL0LEM: Writing thumbnail 0 to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM_0.jpg
[youtube] KKushcL0LEM: Downloading thumbnail 1 ...
[youtube] KKushcL0LEM: Writing thumbnail 1 to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM_1.jpg
[youtube] KKushcL0LEM: Downloading thumbnail 2 ...
[youtube] KKushcL0LEM: Writing thumbnail 2 to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM_2.jpg
[youtube] KKushcL0LEM: Downloading thumbnail 3 ...
[youtube] KKushcL0LEM: Writing thumbnail 3 to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM_3.jpg
[youtube] KKushcL0LEM: Downloading thumbnail 4 ...
[youtube] KKushcL0LEM: Writing thumbnail 4 to: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM_4.jpg
[debug] Invoking downloader on u'https://r1---sn-hp57ynes.googlevideo.com/videoplayback?expire=1612014513&ei=UQ8VYPylI8bj4QSuupaIBg&ip=195.181.163.8&id=28abac85c2f42c43&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=qz&mm=31%2C29&mn=sn-hp57ynes%2Csn-hp57knz6&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=2376250&vprv=1&mime=video%2Fwebm&ns=wHvbZN50NrCUTsXWGYG9z1EF&gir=yes&clen=1008362402&dur=9466.999&lmt=1611472258978882&mt=1611992438&fvip=1&keepalive=yes&c=WEB&txp=7316222&n=izT3StC3yO_QIIplj&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgDVUbwXZnCwmE66-r4dl2qB1gHAhQt_O-cyclmCHD7KkCICesy3nOT0M1Y4wp8Cziy8QOKocpWduIUDvv3qdnYyc7&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaMkf3_ErfLDC2_k_4xQc8z92oE4uSXyX08sqXti8FMoCIHHL-g5vyL5Z_GwVHx7uvsdKRHWnoSRcm4jqhDtkg7TY&ratebypass=yes'
[download] Sleeping 21.44 seconds...
[download] Destination: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.f303
[download] 100% of 961.65MiB in 08:24
[debug] Invoking downloader on u'https://r1---sn-hp57ynes.googlevideo.com/videoplayback?expire=1612014513&ei=UQ8VYPylI8bj4QSuupaIBg&ip=195.181.163.8&id=28abac85c2f42c43&itag=251&source=youtube&requiressl=yes&mh=qz&mm=31%2C29&mn=sn-hp57ynes%2Csn-hp57knz6&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=2376250&vprv=1&mime=audio%2Fwebm&ns=wHvbZN50NrCUTsXWGYG9z1EF&gir=yes&clen=45920881&dur=9467.021&lmt=1611471738994973&mt=1611992438&fvip=1&keepalive=yes&c=WEB&txp=7311222&n=izT3StC3yO_QIIplj&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgEYStcInS2wiFRIMX0GIRuYbgdMQ1_3MwBlXhxw70SNkCIQDV3ErRgx8xHFLPvA5M7dBSkjE2l7EfxflrxsqKGZ7h_g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaMkf3_ErfLDC2_k_4xQc8z92oE4uSXyX08sqXti8FMoCIHHL-g5vyL5Z_GwVHx7uvsdKRHWnoSRcm4jqhDtkg7TY&ratebypass=yes'
[download] Sleeping 17.36 seconds...
[download] Destination: 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.f251
[download] 100% of 43.79MiB in 00:24
[Merger] Merging formats into "00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.f303' -i 'file:00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.f251' -c copy -map '0:v:0' -map '1:a:0' 'file:00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.temp.mkv'
Deleting original file 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.f251 (pass -k to keep)
Deleting original file 00001 20210123 【WATCHALONG】SE7EN Detective movie!!!!/KKushcL0LEM.f303 (pass -k to keep)
ERROR: 'ascii' codec can't decode byte 0xe3 in position 113: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 950, in wrapper
    return func(self, *args, **kwargs)
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 987, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 1026, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 1897, in process_video_result
    self.process_info(new_info)
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 2393, in process_info
    self.post_process(dl_filename, info_dict, files_to_move)
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 2501, in post_process
    info = self.run_pp(MoveFilesAfterDownloadPP(self, files_to_move), info, files_to_move)[1]
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 2468, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/leian/.local/lib/python2.7/site-packages/youtube_dlc/postprocessor/movefilesafterdownload.py", line 33, in run
    oldfile, newfile = compat_str(oldfile), compat_str(newfile)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 113: ordinal not in range(128)
```

## Description

This problem started occurring a few days ago and it has been the case for every livestream VOD I am downloading since then. The live chat used to be downloaded previously unless it was not made available by the channel owner but that wasn't the case for the videos I am downloading. The UnicodeDecodeError also started appearing and only disappears when I use python3. Though, I have noticed that when I use python3 the video format selected is different. Instead of 303+251 formats being selected, it chooses 299+251.

NOTE: The video I downloaded from my log is a video that I have downloaded before and youtube-dlc was able to download live chat and the UnicodeDecodeError didn't show up back then. I used the same configuration as before.

**Comment by pukkandan** [comment] 2021-02-07 08:46
opened 6 days ago? Why the hell didn't github notify me. I will look into it asap

**Comment by pukkandan** [comment] 2021-02-07 08:58
Ok, so you have reported 3 issues.
1. Live chat not downloading - This has been fixed in the latest release
2. 'ascii' codec can't decode byte - This is a compatibility issue with how python2 handles unicode. I will need to figure out how to actually fix this. In the meantime, use either python3 or `--restrict-filenames` 
3. py2 and py3 downloads different formats - No idea why this happens. Will investigate

**Comment by pukkandan** [comment] 2021-02-07 11:25
I have fixed the compat issue. 

Close this issue once you confirm that it is fixed

---

>  I have noticed that when I use python3 the video format selected is different. Instead of 303+251 formats being selected, it chooses 299+251.

I am unable to reproduce this.

```
$ python -m youtube_dlc -f "bestvideo+(bestaudio[asr=48000]/bestaudio)/bestaudio[ext=opus]/best" --merge-output-format "mkv" -v KKushcL0LEM
[debug] Command-line config: [u'-f', u'bestvideo+(bestaudio[asr=48000]/bestaudio)/bestaudio[ext=opus]/best', u'--merge-output-format', u'mkv', u'-v', u'KKushcL0LEM']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.02.04
[debug] Git HEAD: fd4ebabd7
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] KKushcL0LEM: Downloading webpage
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 303+251
[download] 【WATCHALONG】SE7EN Detective movie!!!! [KKushcL0LEM].mkv has already been downloaded

$ python3 -m youtube_dlc -f "bestvideo+(bestaudio[asr=48000]/bestaudio)/bestaudio[ext=opus]/best" --merge-output-format "mkv" -v KKushcL0LEM
[debug] Command-line config: ['-f', 'bestvideo+(bestaudio[asr=48000]/bestaudio)/bestaudio[ext=opus]/best', '--merge-output-format', 'mkv', '-v', 'KKushcL0LEM']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.02.04
[debug] Git HEAD: fd4ebabd7
[debug] Python version 3.8.5 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] KKushcL0LEM: Downloading webpage
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 303+251
[download] 【WATCHALONG】SE7EN Detective movie!!!! [KKushcL0LEM].mkv has already been downloaded
```

Make a new issue with relevant verbose log if the issue persists

**Closed** 2021-02-07 18:36 UTC
Labels: bug

**Comment by CetaceanNation** [comment] 2021-02-13 23:29
Sorry to bump this, I am having the live_chat issue on the latest version. Let me know if I should move this to somewhere different.
## Checklist
- [x] I've verified that I'm running yt-dlp version **2021.02.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ
## Verbose log
```
youtube-dlc --cookies '/mnt/j/cookies.txt' --retries 10 --fragment-retries 10 --write-sub --sub-lang 'en,live_chat' --sub-format 'vtt/json/best' --skip-download --verbose s9w2oIVjhLg
[debug] Command-line config: ['--cookies', '/mnt/j/cookies.txt', '--retries', '10', '--fragment-retries', '10', '--write-sub', '--sub-lang', 'en,live_chat', '--sub-format', 'vtt/json/best', '--skip-download', '--verbose', 's9w2oIVjhLg']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.02.09
[debug] Python version 3.8.5 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] s9w2oIVjhLg: Downloading webpage
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
WARNING: en subtitles not available for s9w2oIVjhLg
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) 303+251
[info] Writing video subtitles to: [Journey To The Savage Planet]  DUM² [s9w2oIVjhLg].live_chat.json
[debug] Invoking downloader on None
[youtube_live_chat_replay] Downloading live chat
[youtube_live_chat_replay] Total fragments: unknown (live)
[download] Destination: [Journey To The Savage Planet]  DUM² [s9w2oIVjhLg].live_chat.json
[download] 1.17MiB at  2.45MiB/s (00:00)[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dlc/__main__.py", line 19, in <module>
    youtube_dlc.main()
  File "/usr/local/bin/youtube-dlc/youtube_dlc/__init__.py", line 548, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/__init__.py", line 538, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2465, in download
    res = self.extract_info(
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 997, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process, info_dict)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1004, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1041, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1073, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1943, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2154, in process_info
    dl(sub_filename, sub_info, subtitle=True)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2120, in dl
    return fd.download(name, info, subtitle)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/downloader/common.py", line 375, in download
    return self.real_download(filename, info_dict), True
  File "/usr/local/bin/youtube-dlc/youtube_dlc/downloader/youtube_live_chat.py", line 111, in real_download
    success, continuation_id, offset = download_and_parse_fragment(url, frag_index)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/downloader/youtube_live_chat.py", line 87, in download_and_parse_fragment
    self.report_error('giving up after %s fragment retries' % fragment_retries)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 723, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 685, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

```
## Description
Downloaded the release from Github and placed in `/usr/local/bin/` because installing via pip3 does not get the latest version. Similar to @believableapparent I'm also trying to download Hololive vods. Had a period of time where this was an issue previously but an update resolved it, now it's back again. Using an example where I just try to download the live_chat and nothing else.
