### ISSUE TITLE
Conflicts with youtube_dlc-2021.01.16 - installs files with the same names

### ISSUE THREAD

**Issue by yurivict** [pukkandan/yt-dlp#61] opened 2021-02-08 18:30 UTC
It is called ```yt-dlp``` but it installs files with names matching the other project:
```
===>   Registering installation for yt-dlp-2021.02.04
Installing yt-dlp-2021.02.04...
pkg-static: yt-dlp-2021.02.04 conflicts with youtube_dlc-2021.01.16 (installs files into the same place).  Problematic file: /usr/local/bin/youtube-dlc
*** Error code 1
```

How different are these projects?

**Comment by pukkandan** [comment] 2021-02-08 18:42
This project was created as a continuation of youtube-dlc since its development seems to have ceased.
I am still using the same binary and module names. If someone is willing to make a PR fixing this, I would be glad to merge it

See also https://github.com/pukkandan/yt-dlp/issues/34
I am closing this issue as a duplicate of that. We can continue the conversation there if you wish

**Closed by pukkandan** 2021-02-08 18:42 UTC

**Comment by pukkandan** [comment] 2021-02-24 21:45
The module has now been changed to yt-dlp. There should be no conflicts in the latest version
